#!/usr/bin/env bash
set -Eeuo pipefail
trap cleanup EXIT

#####################
### Configuration ###
#####################

# Directories
LIB_DIR="${LIB_DIR:-lib}"

# EventBridge vars
RULE_NAME=${RULE_NAME:-"aws-iam-monitor-rule"}

# Test vars
TEST_USER="${TEST_USER:-eventbridge-test-user-$(date +%s)}"

# CloudWatch vars
START_TIME=$(date -u -d "10 minutes ago" +"%Y-%m-%dT%H:%M:%SZ")
END_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
WAIT_SECONDS="${WAIT_SECONDS:-120}"

######################
### !Configuration ###
######################

# Load scripts
if [[ -s "${LIB_DIR}/common" ]]; then
  # shellcheck disable=SC1091
  . "${LIB_DIR}/common"
else
  msg "[ERROR] Missing Script: '${LIB_DIR}/common'"
  exit 1
fi
load_script "${LIB_DIR}/logger"

# shellcheck disable=SC2329
cleanup() {
  msg "[INFO] Cleaning up IAM test user..."

  if aws iam get-user \
    --user-name "$TEST_USER" \
    >/dev/null 2>&1; then

    aws iam delete-user \
      --user-name "$TEST_USER" \
      >/dev/null

    msg "[SUCCESS] Deleted IAM user: ${TEST_USER}"

  else
    msg "[INFO] IAM user already removed"
  fi
}

# shellcheck disable=SC2329
countdown() {
  local SECONDS_LEFT="$1"

  msg INFO "Waiting ${SECONDS_LEFT}s for CloudTrail/EventBridge processing..."

  while [[ "$SECONDS_LEFT" -gt 0 ]]; do

    msg INFO "Processing in ${SECONDS_LEFT}s..."

    sleep 1

    SECONDS_LEFT=$((SECONDS_LEFT - 1))

  done

  printf "\r"
  msg SUCCESS "CloudTrail/EventBridge processing completed"
}

msg INFO " Creating IAM test user: ${TEST_USER}"

aws iam create-user \
  --user-name "$TEST_USER" >/dev/null

msg INFO "IAM user created"

countdown "$WAIT_SECONDS"

msg INFO "Checking EventBridge matched events"

MATCHED_EVENTS=$(
  aws cloudwatch get-metric-statistics \
    --namespace AWS/Events \
    --metric-name MatchedEvents \
    --dimensions Name=RuleName,Value=aws-iam-monitor-rule \
    --statistics Sum \
    --period 300 \
    --start-time "$START_TIME" \
    --end-time "$END_TIME" \
    --output json |
    jq '[.Datapoints[].Sum] | add // 0'
)

if (($(printf "%.0f" "$MATCHED_EVENTS") > 0)); then
  msg SUCCESS " EventBridge received IAM event"
  msg INFO "MatchedEvents: ${MATCHED_EVENTS}"
  exit 0
fi

msg ERROR "EventBridge did not receive IAM event"
msg ERROR "MatchedEvents: ${MATCHED_EVENTS}"

exit 1
