#!/usr/bin/env bash
# =========================================
# .FILE
#   setup_iam
#
# .SYNOPSIS
#   AWS IAM environment setup automation script
#
# .DESCRIPTION
#   Creates and configures IAM users, roles, and policies
#   from a CSV configuration file.
#
#   This script is part of IAMSentinel, a real-time AWS IAM
#   auditing and monitoring project. It prepares IAM resources
#   that generate CloudTrail events for security monitoring.
#
# .INPUTS
#   users.csv
#   policies/*.json
#   lib/*
#
# .OUTPUTS
#   Creates AWS IAM users, roles, and policies.
#   Outputs execution logs to stdout.
#
# .NOTES
#   Project       : aws-iam-monitor
#   Version       : 1.0
#   Author        : @ZouariOmar (zouariomar20@gmail.com)
#   Created       : 08/07/2026
#   Change Log    : 1.0 Initial release
#
# .EXAMPLE
#   ./setup_iam
#
# .REQUIREMENTS
#   - AWS CLI v2
#   - Python
#   - Configured AWS credentials
#   - IAM permissions:
#       iam:CreateUser
#       iam:CreateRole
#       iam:CreatePolicy
#       iam:AttachUserPolicy
#       iam:AttachRolePolicy
#
# shellcheck disable=SC1090
# =========================================

set -e

# ========================
# === Custom conf part ===
# ========================

USERS_CSV_FILE="users.csv"
POLICY_DIR="policies"
LIB_DIR="lib"
AWS_ACCOUNT_ID=""

# =========================
# === !Custom conf part ===
# =========================

# =================
# === Load libs ===
# =================

load_script() {
  local SCRIPT="$1"

  if [[ -s "$SCRIPT" ]]; then
    . "$SCRIPT"
    msg SUCCESS "'$SCRIPT' Loaded successfully!"
  else
    msg ERROR "Missing Script: '$SCRIPT'"
    exit 1
  fi
}

# ==================
# === !Load libs ===
# ==================

# =====================
# === AWS-IAM Setup ===
# =====================

check_aws_auth() {
  msg INFO "Checking AWS credentials..."

  if aws sts get-caller-identity >/dev/null 2>&1; then

    AWS_ACCOUNT_ID=$(aws sts get-caller-identity \
      --query Account \
      --output text)

    USER=$(aws sts get-caller-identity \
      --query Arn \
      --output text)

    msg SUCCESS "AWS authentication successful"
    msg INFO "Account: $AWS_ACCOUNT_ID"
    msg INFO "Identity: $USER"

  else
    msg ERROR "AWS credentials are not configured"
    msg INFO "Run: aws configure"
    exit 1
  fi
}

create_policy() {
  POLICY_NAME=$1
  POLICY_FILE="$POLICY_DIR/${POLICY_NAME}.json"

  if [[ ! -s "$POLICY_FILE" ]]; then
    msg ERROR "Policy file missing or empty: $POLICY_FILE"
    exit 1
  fi

  if aws iam get-policy \
    --policy-arn arn:aws:iam::"$AWS_ACCOUNT_ID":policy/"$POLICY_NAME" \
    >/dev/null 2>&1; then

    msg INFO "Policy exists: https://console.aws.amazon.com/iam/home#/policies/${POLICY_NAME}"
    return
  fi

  if [ ! -f "$POLICY_FILE" ]; then
    msg ERROR "Missing policy file: $POLICY_FILE"
    exit 1
  fi

  aws iam create-policy \
    --policy-name "$POLICY_NAME" \
    --policy-document file://"$POLICY_FILE"

  msg SUCCESS "Created Policy: https://console.aws.amazon.com/iam/home#/policies/${POLICY_NAME}"
}

create_role() {
  ROLE_NAME=$1
  POLICY_NAME=$2

  if aws iam get-role \
    --role-name "$ROLE_NAME" >/dev/null 2>&1; then

    msg INFO "Role exists: https://console.aws.amazon.com/iam/home#/roles/${ROLE_NAME}"
    return
  fi

  aws iam create-role \
    --role-name "$ROLE_NAME" \
    --assume-role-policy-document file://trust-policy.json

  aws iam attach-role-policy \
    --role-name "$ROLE_NAME" \
    --policy-arn arn:aws:iam::"$AWS_ACCOUNT_ID":policy/"$POLICY_NAME"

  msg SUCCESS "Created Role: https://console.aws.amazon.com/iam/home#/roles/${ROLE_NAME}"
}

create_user() {
  USERNAME=$1
  POLICY_NAME=$2

  if aws iam get-user \
    --user-name "$USERNAME" >/dev/null 2>&1; then

    msg INFO "User exists: https://console.aws.amazon.com/iam/home#/users/${USERNAME}"
    msg "----------------------------------"
    return
  fi

  aws iam create-user --user-name "$USERNAME"

  aws iam attach-user-policy \
    --user-name "$USERNAME" \
    --policy-arn arn:aws:iam::"$AWS_ACCOUNT_ID":policy/"$POLICY_NAME"

  msg SUCCESS "Created User: https://console.aws.amazon.com/iam/home#/users/${USERNAME}"
  msg "----------------------------------"
}

# ======================
# === !AWS-IAM Setup ===
# ======================

main() {
  load_script "${LIB_DIR}/logger"
  load_script "${LIB_DIR}/requirements"
  msg ".\n.\n."

  check_aws_auth
  msg ".\n.\n."

  tail -n +2 "$USERS_CSV_FILE" | while IFS=', ' read -r USER ROLE POLICY; do
    msg INFO "USER: $USER | ROLE: $ROLE | POLICY: $POLICY"
    msg "."

    create_policy "$POLICY"
    create_role "$ROLE" "$POLICY"
    create_user "$USER" "$POLICY"
  done

  msg SUCCESS "IAM Setup Complete!"
  msg INFO "IAM Console: https://console.aws.amazon.com/iam/home"
  msg INFO "Users      : https://console.aws.amazon.com/iam/home#/users"
  msg INFO "Roles      : https://console.aws.amazon.com/iam/home#/roles"
  msg INFO "Policies   : https://console.aws.amazon.com/iam/home#/policies"
}

# Run all
main
